services:
  - type: web
    name: orgtool-web
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_HOST
        fromService:
          type: web
          name: dealership-tool-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_API_NAMESPACE
        value: /orgtool
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
